name: CI/CD

on:
  push:
    branches:
      - dev

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: echo
        uses: echo "before Checkout"

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: echo
        uses: echo "before Set up Node.js"

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: echo
        uses: echo "before Install dependencies"

      - name: Install dependencies
        run: npm install

      - name: echo
        uses: echo "before IRun the tests"

      - name: Run the tests
        run: npm test

      - name: echo
        uses: echo "before Build"

      - name: Build
        run: npm run build

#      - uses: echo "before Deploy"
#
#     - name: Deploy
#       run:
#          git remote set-url origin https://${github_token}@github.com/${repository}
#          npm run deploy
#       env:
#          github_token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
#          repository: ${{ github.repository }}
